language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - DJANGO_SETTINGS_MODULE=IngressToolBoxAPI.settings

script:
  - python runtests.py
  - coverage run --source=. manage.py test

after_success:
  - coveralls

branches:
  only:
    - master
    - dev