# Generated by Django 2.0.5 on 2018-06-02 06:21

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=128, verbose_name='pass code')),
                ('message', models.CharField(max_length=512, verbose_name='信息')),
                ('checked', models.BooleanField(default=False, verbose_name='已验证')),
            ],
            options={
                'verbose_name': 'PassCode',
                'verbose_name_plural': 'PassCode',
            },
        ),
    ]
