# Generated by Django 2.0.5 on 2018-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('weight', models.SmallIntegerField(default=1, verbose_name='权重')),
                ('hide', models.BooleanField(default=False, verbose_name='隐藏')),
            ],
        ),
        migrations.AddField(
            model_name='passcode',
            name='tags',
            field=models.ManyToManyField(to='codes.Tag'),
        ),
    ]
